    FROM node:lts-alpine
    # FROM keymetrics/pm2:latest-alpine

    RUN npm install pm2 -g

    COPY . /usr/src/nuxt/

    WORKDIR /usr/src/nuxt/

    RUN npm install

    EXPOSE 8080

    RUN npm run build
    # start the app
    # RUN pm2-runtime start pm2.json
    CMD ["npm","run","start"]