spring:
  datasource:
    url: jdbc:mysql://K02D1031.p.ssafy.io:3306/youtube_test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 02d103
  social:
    google:
      client_id: 412300629283-sd7m25vk2m7uijmt9lfpjkscvq3sr6vv.apps.googleusercontent.com
      client_secret: XHhA4GlqOVJZkVmhHHuP1uxj
      redirect: /youtube/google/code
      code_redirect: /youtube/google/code
      code_result_redirect: /social/login/google/code/result
      google_api_v2_scope: https://www.googleapis.com/auth/youtube
      accept: application/x-www-form-urlencoded
      youtube_data_api_v3: https://www.googleapis.com/youtube/v3/
      url:
        authorize: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        google_api_v2_user: https://api.twitch.tv/kraken/users
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 412300629283-sd7m25vk2m7uijmt9lfpjkscvq3sr6vv.apps.googleusercontent.com
            clientSecret: XHhA4GlqOVJZkVmhHHuP1uxj
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
              - "https://www.googleapis.com/auth/youtube"
          facebook:
            clientId: 250967889352419
            clientSecret: 921b243471998d35132e143b7068c429
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: Iv1.8c7c26c45dc6a8fb
            clientSecret: e0106936012ad904567205a6e793efb0acdbff4c
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
#          twitch:
#            clientId: db8sw2xqe82gk1x78mkubkr5xh545p
#            clientSecret: bdweu354ghkwk1152bx5rmfdmmtib5
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - user:read:email
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v7.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v7.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v7.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
#          twitch:
#            authorizationUri: https://id.twitch.tv/oauth2
#            tokenUri: https://id.twitch.tv/validate
#            userInfoUri: https://id.twitch.tv/
app:
  auth:
    tokenSecret: C45FF95D3AE216CC621748587CE42
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect